export const ADD_HOTEL_TO_STORE = 'ADD_HOTEL_TO_STORE'
export const REMOVE_HOTEL_FROM_STORE = 'REMOVE_HOTEL_FROM_STORE'
export const ADD_HOTEL_ROOM_TO_STORE = 'ADD_HOTEL_ROOM_TO_STORE'
export const BOOKED_ROOM = 'BOOKED_ROOM'